language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install codecov
# command to run tests
script: 
  - nosetests --with-coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
